"use strict";

const DIRECTION_NONE = "0";
const DIRECTION_LEFT = "left";
const DIRECTION_RIGHT = "right";
const DIRECTION_UP = "up";
const DIRECTION_DOWN = "down";
const DIRECTION_CLOCKWISE = 1;
const DIRECTION_COUNTER_CLOCKWISE = -1;

const DIRECTION_HORIZONTAL = [DIRECTION_LEFT, DIRECTION_RIGHT];
const DIRECTION_VERTICAL = [DIRECTION_UP, DIRECTION_DOWN];
const DIRECTION_ALL = [DIRECTION_LEFT, DIRECTION_RIGHT, DIRECTION_UP, DIRECTION_DOWN];

const GESTURE_STATE_POSSIBLE = "possible";
const GESTURE_STATE_BLOCKED = "blocked";
